---
title: "Biogeografía y Macroecología"
description: "Licenciatura en Ecología"
author: "Gerardo Martín"
output:
   prettydoc::html_pretty:
      theme: hpstr
      highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Programa de [Biogeografía](Biogeografia.pdf) y de [Macroecología](Macroecologia.pdf).

# Procesos en biogeografía

1. [Extinción](Extincion.pdf)

2. [Dispersión](Dispersion.pdf)

3. [La expansión de rangos](Expansion.pdf)

4. [La radiación adaptativa](Radiacion.pdf)

# Procesos que determinan los patrones de distribución a grandes escalas

1. [Riqueza de especies a diferentes escalas](Riqueza-escalas.pdf)
2. [Relación especie – área](Spp-area.pdf)
3. [Variación de la riqueza de especies](Variacion-lat-lon-riqueza.pdf)
4. Implicaciones de los procesos históricos para la distribución de la diversidad

# Métodos para analizar patrones ecológicos a grandes escalas

1. Bases de datos de diversidad

    - [Puntos](Datos-diversidad-puntos.html)
    
    - [Polígonos](Datos-diversidad-poligonos.html)
    
2. [Aplicaciones de los sistemas de información geográfica](Aplicaciones-SIG.html)

    - [Modelación de áreas de distrobución](Tutorial-aplicaciones/Tutorial-SDM.R)

3. [Análisis y modelación de los sistemas ecológicos a grandes escalas espaciales y temporales](Analisis-modelacion-macro.html)
